sudo: required
services:
  - docker

before_install:
  - docker build -t marutp/docker-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run marutp/docker-test npm run test   -- --coverage

after_success:
  - docker build -t marutp/docker-web-client ./client
  - docker build -t marutp/docker-web-server ./server
  - docker build -t marutp/docker-web-nginx ./nginx
  - docker build -t marutp/docker-web-worker ./worker
  # log to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push marutp/docker-web-client
  - docker push marutp/docker-web-server
  - docker push marutp/docker-web-nginx
  - docker push marutp/docker-web-worker
